apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: front-end-ingress
  namespace: sock-shop
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: front-end
          servicePort: 80